# Generated by Django 4.0.6 on 2022-08-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicemgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(blank=True, choices=[('Receipt', 'Receipt'), ('Invoice', 'Invoice')], default='', max_length=50, null=True),
        ),
    ]
